const { Client } = require('ssh2');
const config = { host: '62.72.25.117', port: 65002, username: 'u256167180', password: '4_m_XMkgux@.AgC' };
const conn = new Client();
conn.on('ready', () => {
    conn.exec('cd domains/sukounalbunyan.ae/public_html/backend && echo "PD9waHAKcmVxdWlyZSBfX0RJUl9fIC4gJy92ZW5kb3IvYXV0b2xvYWQucGhwJzsKXCA9IHJlcXVpcmVfb25jZSBfX0RJUl9fIC4gJy9ib290c3RyYXAvYXBwLnBocCc7ClwgPSBcLT5tYWtlKElsbHVtaW5hdGVcQ29udHJhY3RzXENvbnNvbGVcS2VybmVsOjpjbGFzcyk7ClwtPmJvb3RzdHJhcCgpOwoKXEFwcFxNb2RlbHNcU2V0dGluZzo6d2hlcmUoJ2NyZWF0ZWRfYnknLCA3KS0+ZGVsZXRlKCk7ClxOb2JsZVxQcm9kdWN0U2VydmljZVxNb2RlbHNcUHJvZHVjdFNlcnZpY2VVbml0Ojp3aXRob3V0R2xvYmFsU2NvcGVzKCktPndoZXJlKCdjcmVhdGVkX2J5JywgNyktPmRlbGV0ZSgpOwpcTm9ibGVcUHJvZHVjdFNlcnZpY2VcTW9kZWxzXFByb2R1Y3RTZXJ2aWNlQ2F0ZWdvcnk6OndpdGhvdXRHbG9iYWxTY29wZXMoKS0+d2hlcmUoJ2NyZWF0ZWRfYnknLCA3KS0+ZGVsZXRlKCk7ClxOb2JsZVxQcm9kdWN0U2VydmljZVxNb2RlbHNcUHJvZHVjdFNlcnZpY2VJdGVtOjp3aXRob3V0R2xvYmFsU2NvcGVzKCktPndoZXJlKCdjcmVhdGVkX2J5JywgNyktPmRlbGV0ZSgpOwpcQXBwXE1vZGVsc1xXYXJlaG91c2U6OndpdGhvdXRHbG9iYWxTY29wZXMoKS0+d2hlcmUoJ2NyZWF0ZWRfYnknLCA3KS0+ZGVsZXRlKCk7ClxOb2JsZVxMZWFkXE1vZGVsc1xQaXBlbGluZTo6d2hlcmUoJ2NyZWF0ZWRfYnknLCA3KS0+ZGVsZXRlKCk7ClxOb2JsZVxMZWFkXE1vZGVsc1xMZWFkU3RhZ2U6OndoZXJlKCdjcmVhdGVkX2J5JywgNyktPmRlbGV0ZSgpOwpcTm9ibGVcTGVhZFxNb2RlbHNcRGVhbFN0YWdlOjp3aGVyZSgnY3JlYXRlZF9ieScsIDcpLT5kZWxldGUoKTsKXE5vYmxlXExlYWRcTW9kZWxzXExlYWQ6OndoZXJlKCdjcmVhdGVkX2J5JywgNyktPmRlbGV0ZSgpOwpcTm9ibGVcTGVhZFxNb2RlbHNcRGVhbDo6d2hlcmUoJ2NyZWF0ZWRfYnknLCA3KS0+ZGVsZXRlKCk7ClxOb2JsZVxSZW50YWxcTW9kZWxzXFJlbnRhbENvbnRyYWN0Ojp3aXRob3V0R2xvYmFsU2NvcGVzKCktPndoZXJlKCdjcmVhdGVkX2J5JywgNyktPmVhY2goZnVuY3Rpb24gKFwpIHsgXC0+aXRlbXMoKS0+ZGVsZXRlKCk7IFwtPmRlbGV0ZSgpOyB9KTsKXE5vYmxlXFRhc2tseVxNb2RlbHNcUHJvamVjdDo6d2l0aG91dEdsb2JhbFNjb3BlcygpLT53aGVyZSgnY3JlYXRlZF9ieScsIDcpLT5kZWxldGUoKTsKXE5vYmxlXEFjY291bnRcTW9kZWxzXEN1c3RvbWVyOjp3aXRob3V0R2xvYmFsU2NvcGVzKCktPndoZXJlKCdjcmVhdGVkX2J5JywgNyktPmRlbGV0ZSgpOwpcQXBwXE1vZGVsc1xVc2VyOjp3aXRob3V0R2xvYmFsU2NvcGVzKCktPndoZXJlKCdjcmVhdGVkX2J5JywgNyktPmRlbGV0ZSgpOwplY2hvICJEYXRhIENsZWFuZWQuXG4iOw==" | base64 -d > cleanup.php && /opt/alt/php82/usr/bin/php cleanup.php && git pull origin master && /opt/alt/php82/usr/bin/php artisan db:seed --class=DemoRentalDataSeeder --force && rm cleanup.php', (err, stream) => {
        if (err) throw err;
        stream.on('close', (code) => { conn.end(); }).on('data', (data) => { process.stdout.write(data); }).stderr.on('data', (data) => { process.stderr.write(data); });
    });
}).connect(config);
